In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 

In [2]:
from tensorflow import keras

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation
model = keras.Sequential([
    Dense(30, input_shape=(114,)),
    Activation('relu'),
    Dense(1),
    Activation('relu')
])

In [4]:
[alliance_data_events['cafr 1072'.split(" ")[1]].index('cafr'.split(" ")[0])+1]
team = 'cafr 1072'.split(" ")[1]
event = 'cafr 1072'.split(" ")[0]
alliance_data_events[team][alliance_data_events[team].index(event)+1]
                     

NameError: name 'alliance_data_events' is not defined

In [6]:
import numpy as np
alliance_labels = np.load('alliance_dictionary(revised).npy',allow_pickle=True).item()
match_dict = np.load('average match dict(oprs and event averages).npy',allow_pickle = True).item()

In [6]:
#abca 359 for alliance
#abca frc5015 for match_dict
print(alliance_labels['cafr 1072'])
print(match_dict['cafr frc1072'])

1160
[ 5.69375000e+01  1.81250000e+00  1.38750000e+01  1.00000000e+00
  0.00000000e+00  1.00000000e+00  0.00000000e+00  1.00000000e+00
  0.00000000e+00  9.37500000e-01  6.25000000e-02  9.37500000e-01
  6.25000000e-02  9.37500000e-01  6.25000000e-02  1.00000000e+00
  6.25000000e-01  1.00000000e+00  6.25000000e-01  1.00000000e+00
  7.50000000e-01  4.37500000e-01  4.37500000e-01  5.62500000e-01
  5.00000000e-01  9.37500000e-01  9.37500000e-01  9.37500000e-01
  9.37500000e-01  9.37500000e-01  8.12500000e-01  6.25000000e-01
  3.12500000e-01  1.87500000e-01  3.75000000e-01  1.87500000e-01
  2.50000000e-01  1.25000000e-01  3.12500000e-01  1.25000000e-01
  1.25000000e-01  1.25000000e-01  2.50000000e-01  1.25000000e-01
  1.25000000e-01  6.25000000e-02  1.87500000e-01  6.25000000e-02
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  1.73935800e+01  1.18094512e+01  1.46500000e-01  1.65548780e+00
  1.82926829e-02 -1.

In [14]:
#hop frc1072
#data
#hop 1072
#labels

325

In [7]:
data = []
labels = []
'''file = open('Robotics Scouting Funtimes(large).csv')

lines = file.readlines()
for k in range(30):
    words = lines[k].split(',')
    for i in range(19):
        words[i] = float(words[i])
    data.append(np.asarray(words[:-1]))
    labels.append(words[-1])
'''

for key in match_dict:
    try:
        team = key.split(" ")[1][3:]
        event = key.split(" ")[0]
        labels.append(alliance_labels[event+" "+team])
        data.append(match_dict[key])
    except:
        pass
        
    
data = np.asarray(data)
labels = np.asarray(labels)


In [8]:
len(labels)

5536

In [9]:
print(data[57])
print(labels[57])
print(len(data))
print(len(labels))

[ 9.14615385e+01  2.00000000e+00  1.50000000e+01  9.23076923e-01
  7.69230769e-02  3.07692308e-01  6.92307692e-01  4.61538462e-01
  5.38461538e-01  5.38461538e-01  4.61538462e-01  8.46153846e-01
  1.53846154e-01  1.00000000e+00  0.00000000e+00  1.00000000e+00
  5.38461538e-01  6.15384615e-01  6.15384615e-01  9.23076923e-01
  9.23076923e-01  5.38461538e-01  4.61538462e-01  4.61538462e-01
  4.61538462e-01  7.69230769e-01  5.38461538e-01  8.46153846e-01
  6.15384615e-01  1.00000000e+00  6.15384615e-01  2.23076923e+00
  8.46153846e-01  6.15384615e-01  9.23076923e-01  8.46153846e-01
  9.23076923e-01  6.92307692e-01  8.46153846e-01  8.46153846e-01
  5.38461538e-01  3.84615385e-01  8.46153846e-01  6.92307692e-01
  5.38461538e-01  3.84615385e-01  8.46153846e-01  7.69230769e-01
  4.61538462e-01  2.30769231e-01  5.38461538e-01  4.61538462e-01
  5.38461538e-01  3.07692308e-01  6.15384615e-01  4.61538462e-01
  4.34730428e+01  1.40843455e+01  3.34000000e-01  1.09210526e+00
 -4.18353576e-02  4.18353

In [23]:
len(data)

5703

In [56]:
data[0]

array([6.49375000e+01, 1.00000000e+00, 1.25625000e+01, 1.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 9.37500000e-01,
       6.25000000e-02, 8.75000000e-01, 1.25000000e-01, 1.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       7.50000000e-01, 1.00000000e+00, 9.37500000e-01, 1.00000000e+00,
       7.50000000e-01, 9.37500000e-01, 8.75000000e-01, 8.75000000e-01,
       8.12500000e-01, 8.75000000e-01, 7.50000000e-01, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 8.12500000e-01, 2.81250000e+00,
       5.00000000e-01, 1.87500000e-01, 5.00000000e-01, 1.87500000e-01,
       6.25000000e-01, 1.87500000e-01, 4.37500000e-01, 1.25000000e-01,
       1.25000000e-01, 6.25000000e-02, 1.25000000e-01, 1.25000000e-01,
       1.87500000e-01, 0.00000000e+00, 1.87500000e-01, 1.25000000e-01,
       1.25000000e-01, 0.00000000e+00, 6.25000000e-02, 0.00000000e+00,
       1.25000000e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [84]:
labels[0]

80

In [10]:
model.compile(loss='mse', optimizer='adam', metrics=['mae'])
model.fit(data, labels, epochs=500000)

Train on 5536 samples
Epoch 1/500000
5536/5536 [==============================] - 1s 126us/sample - loss: 211784.6921 - mae: 362.4261
Epoch 2/500000
5536/5536 [==============================] - 0s 72us/sample - loss: 90816.6740 - mae: 199.6668
Epoch 3/500000
5536/5536 [==============================] - 0s 67us/sample - loss: 53786.7983 - mae: 163.4488
Epoch 4/500000
5536/5536 [==============================] - 0s 58us/sample - loss: 51020.3762 - mae: 163.6283
Epoch 5/500000
5536/5536 [==============================] - 0s 63us/sample - loss: 49356.6504 - mae: 159.9276
Epoch 6/500000
5536/5536 [==============================] - 0s 73us/sample - loss: 47653.3388 - mae: 156.2436
Epoch 7/500000
5536/5536 [==============================] - 0s 73us/sample - loss: 46250.8650 - mae: 153.0267
Epoch 8/500000
5536/5536 [==============================] - 1s 104us/sample - loss: 45244.8908 - mae: 151.5179
Epoch 9/500000
5536/5536 [==============================] - 1s 94us/sample - loss: 44589.8041 -

KeyboardInterrupt: 

In [1025]:
data = np.load("CCC match data for training.npy",allow_pickle=True)

In [686]:
dank = match_dict['cafr 1072']
'''dank = [73.5,  1. , 13.2,  1. ,  0. ,  1. ,  0. ,  1. ,  0. ,  0.5,  0.5,
        0.8,  0.2,  1. ,  0. ,  1. ,  0.6,  1. ,  0.6,  1. ,  0.7,  0.5,
        0.4,  0.2,  0.2,  0.9,  0.7,  0.8,  0.6,  1. ,  0.5,  1.7,  0.7,
        0.4,  0.5,  0.4,  0.7,  0.5,  0.5,  0.4,  0.5,  0.5,  0.6,  0.6,
        0.5,  0.5,  0.6,  0.6,  0.3,  0.3,  0.4,  0.3,  0.5,  0.3,  0.3,
        0.2]'''
dank = np.asarray([np.asarray(dank)])
np.reshape(dank,(56,))
model.predict(dank)

array([[1145.3971]], dtype=float32)

In [687]:
alliance_data_events['1072']

('cada', 1160, 'caelk', 600, 'cafr', 1160, 'hop', 325, '', 20)

In [11]:
import urllib.request, json, requests
def rank_teams(match_dict):
    d = {}
    for team in match_dict:
        dank = np.reshape(np.asarray(np.asarray(match_dict[team])),(114,1))
        dank = dank.T
        if team.split(" ")[1] == 'frc1072':
            d[team+" fake"] = 10720
        d[team] = model.predict(dank)
    return sorted(d.items(), key = 
             lambda kv:(kv[1], kv[0]))  

            
      

In [1058]:
ccc_match_dict['caelk frc1072']

array([57.4,  1.9, 13.8,  1. ,  0. ,  1. ,  0. ,  1. ,  0. ,  1. ,  0. ,
        1. ,  0. ,  1. ,  0. ,  1. ,  0.5,  1. ,  0.7,  1. ,  0.8,  0.5,
        0.4,  0.5,  0.3,  1. ,  0.6,  1. ,  0.6,  1. ,  0.5,  0.9,  0.5,
        0.1,  0.8,  0.4,  0.5,  0.1,  0.8,  0.4,  0.4,  0. ,  0.4,  0. ,
        0.3,  0. ,  0.4,  0. ,  0.2,  0.2,  0. ,  0. ,  0.3,  0.1,  0. ,
        0. ])

In [74]:
test = (np.reshape(np.asarray(np.asarray(match_dict['hop frc1072'])), (114,1)))

In [75]:
test = test.T
print(test.shape)

(1, 114)


In [77]:
model.predict(test)

array([[120.79628]], dtype=float32)

In [12]:
import urllib.request, json, requests
def rank_teams_new(event):
    d = {}
    user_agent = {'User-agent': 'Mozilla/5.0'}
    key = '?X-TBA-Auth-Key=nkRpKyrwQU3P6XtznbFVHyq57mGz3N6e4kYUCwjigdBR6C50VYZ8FoKngBIySCiU'
    req = urllib.request.Request("https://www.thebluealliance.com/api/v3/event/" + event + "/teams/keys" + key, headers = user_agent)
    with urllib.request.urlopen(req) as url:
        temp = []
        data = json.loads(url.read().decode())
        for team in data:
            try:
                dank = np.reshape(np.asarray(np.asarray(match_dict[event[4:] + " " + team])),(114,1))
                dank = dank.T
                d[team] = model.predict(dank)
            except:
                pass
    return sorted(d.items(), key = 
             lambda kv:(kv[1], kv[0]))  

            
      

In [13]:
import urllib.request, json, requests
def rank_teams_defense(event):
    d = {}
    user_agent = {'User-agent': 'Mozilla/5.0'}
    key = '?X-TBA-Auth-Key=nkRpKyrwQU3P6XtznbFVHyq57mGz3N6e4kYUCwjigdBR6C50VYZ8FoKngBIySCiU'
    req = urllib.request.Request("https://www.thebluealliance.com/api/v3/event/" + event + "/teams/keys" + key, headers = user_agent)
    with urllib.request.urlopen(req) as url:
        temp = []
        data = json.loads(url.read().decode())
        for team in data:
            try:
                temp = team[3:]
                dank = match_dict_defense_updated[event[4:]+" "+temp]
                dank = np.asarray([np.asarray(dank)])
                np.reshape(dank,(59,))
                d[temp] = model.predict(dank)
            except:
                pass
    return sorted(d.items(), key = 
             lambda kv:(kv[1], kv[0]))  

            
      

In [92]:
from keras.models import load_model

#model = model.save('Testing new model large.h5')  # creates a HDF5 file 'my_model.h5'
#del model  # deletes the existing model

# returns a compiled model
# identical to the previous one
#model = load_model('my_model.h5')
#new_model = keras.models.load_model('../Downloads')
model.save('Testing new model large save', save_format='tf')

# Recreate the exact same model
#new_model = keras.models.load_model('path_to_saved_model')



Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: Testing new model large save/assets


In [15]:
rank_teams_new('2019')

[('frc4707', array([[124.8067]], dtype=float32)),
 ('frc2708', array([[172.02614]], dtype=float32)),
 ('frc5512', array([[173.14919]], dtype=float32)),
 ('frc6317', array([[194.22678]], dtype=float32)),
 ('frc7589', array([[230.5247]], dtype=float32)),
 ('frc4150', array([[261.44864]], dtype=float32)),
 ('frc1660', array([[264.0189]], dtype=float32)),
 ('frc5860', array([[269.32742]], dtype=float32)),
 ('frc7858', array([[276.10428]], dtype=float32)),
 ('frc2526', array([[277.1481]], dtype=float32)),
 ('frc1188', array([[279.21823]], dtype=float32)),
 ('frc271', array([[280.28357]], dtype=float32)),
 ('frc7741', array([[296.27753]], dtype=float32)),
 ('frc141', array([[301.1096]], dtype=float32)),
 ('frc4956', array([[301.44946]], dtype=float32)),
 ('frc4311', array([[309.30753]], dtype=float32)),
 ('frc7650', array([[316.03137]], dtype=float32)),
 ('frc4325', array([[318.67252]], dtype=float32)),
 ('frc6802', array([[324.82526]], dtype=float32)),
 ('frc7617', array([[330.90903]], dtyp

In [108]:
ccc_match_dict = np.load('ccc_match_dict(large).npy',allow_pickle=True).item()

In [120]:
rank_teams(ccc_match_dict)

[('caelk frc4643', array([[146.01968]], dtype=float32)),
 ('caelk frc6814', array([[171.38824]], dtype=float32)),
 ('caelk frc1280', array([[173.72409]], dtype=float32)),
 ('caelk frc3598', array([[178.21663]], dtype=float32)),
 ('caelk frc5496', array([[190.00887]], dtype=float32)),
 ('caelk frc6662', array([[203.59158]], dtype=float32)),
 ('caelk frc2813', array([[205.38431]], dtype=float32)),
 ('caelk frc4123', array([[206.5933]], dtype=float32)),
 ('caelk frc701', array([[206.78313]], dtype=float32)),
 ('caelk frc6059', array([[215.24312]], dtype=float32)),
 ('caelk frc2035', array([[215.59056]], dtype=float32)),
 ('caelk frc4159', array([[216.38223]], dtype=float32)),
 ('caelk frc841', array([[220.46046]], dtype=float32)),
 ('caelk frc7667', array([[220.50862]], dtype=float32)),
 ('caelk frc7528', array([[227.80008]], dtype=float32)),
 ('caelk frc5250', array([[237.06761]], dtype=float32)),
 ('caelk frc5274', array([[238.53651]], dtype=float32)),
 ('caelk frc3925', array([[247.774